server:
  port: "8080"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "tutorial"
  sslmode: "disable"

app:
  name: "Production API"
  environment: "development"
  loglevel: "info"

